// <auto-generated />
namespace PST2231A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class videopropertyepisode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(videopropertyepisode));
        
        string IMigrationMetadata.Id
        {
            get { return "202304151751274_video-property-episode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
