// <auto-generated />
namespace PST2231A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class biographyadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(biographyadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202304132131078_biography-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
