// <auto-generated />
namespace PST2231A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class premiseadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(premiseadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202304132135112_premise-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
